### ISSUE TITLE
Build seems to be broken

### ISSUE THREAD

**Issue by ganesheth** [thingweb/thingweb#4]
References to class Metadata are broken.

**Comment by vcharpenay** [comment]
Which Metadata are you referencing?

There used to be `de.thingweb.desc.pojo.Metadata`. All references to `de.thingweb.desc.pojo.*` have been removed, you should have a look at `de.thingweb.thing.*` instead (a new, slightly different Metadata class is defined there).

By the way, I know I did not take all of your changes to the POJOs into account, that is, I did not included stability and JSON-LD `@type` and `@id` in the new structure. The reason is that I couldn't find any reference to those elements in the project. Do you need them elsewhere?

**Comment by ganesheth** [comment]
Sorry, my mistake. My git pull was not correct after switching to newtd branch. Now its ok. Thanks for your response.
